### ISSUE TITLE
Investigate: "ignored" ConsulExceptions in KeyValueClient

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/consul-client#153]
`KeyValueClient` has two locations that catch `ConsulException` and are declared like:

```java
try {
    // the logic
} catch (ConsulException ignored) {
    if (ignored.getCode() != NOT_FOUND_404) {
        throw ignored;
    }
}
```

The question here is whether the exception is just named badly, since clearly it is not always ignored.

**Comment by terezivy** [comment]
yeah I would say something more like can be ignored or the like. It is sort of nebulous either way
